### ISSUE TITLE
【提问】amd显卡可以用这个软件吗

### ISSUE THREAD

**Issue by Fy0808fhyj** [Chenyme/Chenyme-AAMT#10]
我使用开源的whisper 音频转文字软件可以用amd转换，这个软件支持amd显卡吗

**Comment by chenyme** [comment]
你好！该项目利用whisper和faster-whisper作为后端。
使用whisper理论是可以支持的，但是可能需要我后续适配；
但若使用faster-whisper，查阅官方信息后目前是不支持amd显卡的。非常抱歉☹️。
