### ISSUE TITLE
【提问】第一次使用生成视频报错，VPN已开启，该如何解决

### ISSUE THREAD

**Issue by sanlilin** [Chenyme/Chenyme-AAMT#11]
LocalEntryNotFoundError: Cannot find an appropriate cached snapshot folder for the specified revision on the local disk and outgoing traffic has been disabled. To enable repo look-ups and downloads online, pass 'local_files_only=False' as input.

**Comment by chenyme** [comment]
你好！VPN不稳定，可能会导致faster-whisper模型下载失败，该模型需从hugging face下载。
想问下，这段代码是从何时报错的？

**Comment by sanlilin** [comment]
您好，感谢答复。刚才收到你消息我又去试了下，还是同样结果。

**Comment by chenyme** [comment]
很抱歉☹️这是由于网络不稳定导致模型下载失败，除非尝试更稳定的网络。
这可能是因为large模型太大了，加上国内访问hugging face不是很稳定和VPN不稳定的原因，导致模型下载失败。后续可能会考虑模型本地加载来规避国内模型下载失败的问题。
# Todo
- [ ] 本地模型加载
- [ ] 个人微调模型支持

**Comment by m4o9** [comment]
希望能够尽快加入本地模型加载 感谢

**Comment by chenyme** [comment]
你好！项目最新版本[V0.6.2](https://github.com/Chenyme/Chenyme-AAVT/releases/tag/V0.6.2)已支持本地模型加载、个人微调模型功能，感谢你的反馈！
# Todo
- [x] 本地模型加载
- [x] 个人微调模型支持

**Comment by aoout** [comment]
我已经加载了本地模型，可是运行还是出现这个同样的错误
@Chenyme

**Comment by chenyme** [comment]
你好！能否提供一下具体的本地模型目录和该模型的文件截图？
@aoout 你可以重新开一个议题，该议题已关闭，不能及时收到回复。

**Comment by aoout** [comment]
我后续又测试了一下，发现即使是打开了加载本地模型的设置，程序还是试图从huggingface加载模型。这大概就是问题所在。

**Comment by chenyme** [comment]
> 我后续又测试了一下，发现即使是打开了加载本地模型的设置，程序还是试图从huggingface加载模型。这大概就是问题所在。

谢谢你的再次反馈！@aoout 
我已检查源码并定位到问题出处，预计下个版本会修复此问题，非常感谢！
