### ISSUE TITLE
【建议】推荐使用虚拟环境

### ISSUE THREAD

**Issue by IYATT-yx** [Chenyme/Chenyme-AAMT#12]
执行安装文件的时候创建一个专用的虚拟环境，在里面安装依赖包，而不是在全局Python环境中安装

**Comment by chenyme** [comment]
感谢建议！后续会改进

**Comment by chenyme** [comment]
你好！[最新版本](https://github.com/Chenyme/Chenyme-AAVT/releases/tag/V0.6.2)在启动项目时会自动创建新的项目环境，非常感谢您的建议！
