### ISSUE TITLE
【提问】上传视频问题

### ISSUE THREAD

**Issue by cuiikma** [Chenyme/Chenyme-AAMT#13]
上传视频时出现AxiosError: Request failed with status code 403

**Comment by chenyme** [comment]
您好！这个问题可能是由于XSRF（跨站请求伪造）造成的。您可以尝试在`.streamlit/config.toml `中添加下述配置来禁用XSRF保护。

```

[server]
enableXsrfProtection = false
enableCORS = false

```

具体情况可参考streamlit:[discuss.streamlit.io](https://discuss.streamlit.io/t/axioserror-request-failed-with-status-code-403/38112)内的问题反馈。
