### ISSUE TITLE
【错误】0.6.2版本生成视频问题

### ISSUE THREAD

**Issue by ZoraZora59** [Chenyme/Chenyme-AAMT#16]
我在使用最新的版本包0.6.2版本进行视频字幕生成时遇到问题，配置如下

![image](https://github.com/Chenyme/Chenyme-AAVT/assets/26945938/c2a161c0-ce1f-4484-b4c1-50b3111230bc)

视频生成的过程中，我观察到前几分钟我的gpu cuda利用率有明显上升，但是后半段则只有CPU占用。

视频生成完毕后，通过VLC等外部播放器打开视频文件时，会发现字幕分成了“视频画面上的字幕”和“视频外挂的字幕”两部分，重叠显示在播放器窗口上。

1. 视频生成过程中如何更好地利用GPU，避免低效的CPU时段。
2. 视频生成时可否不将字幕压制到画面内，仅保留外挂字幕即可

**Comment by ZoraZora59** [comment]
在VLC上的字幕重叠效果如图
![image](https://github.com/Chenyme/Chenyme-AAVT/assets/26945938/ce32ee6d-6f53-460b-a0ca-7076df1e60ec)

**Comment by ZoraZora59** [comment]
第二个问题似乎可以简单的将ffmpeg命令修改为`ffmpeg -i "uploaded.mp4" -i output.srt -c copy output.mp4`

**Comment by chenyme** [comment]
你好！感谢反馈◕‿◕
1. 生成时后半段只有CPU占用，可能是流程进行到了FFmpeg合并视频阶段，该项目在FFmpeg合并时未采用Nvidia CUDA GPU 加速。后续我也会对CUDA加速效果进行测试验证。
2. 字幕重叠显示在播放器窗口上，是因为目前视频生成时字幕采用的是硬字幕输出，未采用软字幕（外挂字幕）输出。当然ffmpeg可以很方便的输出这两种的视频字幕效果，后续版本会加入软字幕（外挂字幕）功能。
