### ISSUE TITLE
【错误】爆出openai_key不存在

### ISSUE THREAD

**Issue by CreateGuy** [Chenyme/Chenyme-AAMT#17]
我已经在浏览器中输入了key，或者在config的配置文件找中配置，但是在主页中问AI小助手还是会报错，生成视频也一样，爆出key不存在

![1](https://github.com/Chenyme/Chenyme-AAVT/assets/56995260/b5353e64-5042-4eec-8d94-949c0ca805a3)

**Comment by chenyme** [comment]
感谢反馈！刚测试了一下AI小助手确实存在`openai_key`丢失问题，该问题已在[V0.6.3_Fixbug](https://github.com/Chenyme/Chenyme-AAVT/releases/tag/V0.6.3_Fixbug)版本里解决，谢谢你的指出！
此外，我在`音频`和`视频`界面能正常使用助手和翻译，并未出现丢失情况，能否提供更详细的报错情况？**您可以在`V0.6.3_Fixbug`版本中使用后观察是否还有该情况发生，若仍出现还请继续向我反馈更多细节，非常感谢(≧∇≦)ﾉ。**
