### ISSUE TITLE
【提问】无法使用chatgpt中转站

### ISSUE THREAD

**Issue by GuoMieClub** [Chenyme/Chenyme-AAMT#19]
![image](https://github.com/Chenyme/Chenyme-AAVT/assets/54953020/1af8821e-28b8-4353-9635-ee93c19c2845)
![image](https://github.com/Chenyme/Chenyme-AAVT/assets/54953020/f87eeec3-8f37-4d2e-8340-551ec58b44e3)
已确认config里openai_base被正确修改。但仍然报密钥错误

**Comment by chenyme** [comment]
你好！请确认你的key是否正确或者是否失效。
我在最新版本中已测试中转功能可以正常使用，并且能够正确得到翻译结果。请确认你的key或者更换key重新使用，如仍报错，请继续向我反馈~感谢！
![dbbf1f9ca8838ae7a854bea332e13d2](https://github.com/Chenyme/Chenyme-AAVT/assets/118253778/ddb7806a-d904-4d1f-aa89-4826f77e1a5e)
