### ISSUE TITLE
【错误】运行 install.bat 会有报错

### ISSUE THREAD

**Issue by hezeen** [Chenyme/Chenyme-AAMT#2]
python 3.12版本会在安装faster-whisper失败，3.11版本可以

**Comment by chenyme** [comment]
你好！faster-whisper的官方建议是python >= 3.8，安装失败可能是由于PyAV版本不兼容python 3.12导致的，你可以查看https://github.com/SYSTRAN/faster-whisper/issues/571 或者 https://github.com/SYSTRAN/faster-whisper/pull/679 寻找更多信息。

**Comment by hezeen** [comment]
感谢

**Comment by chenyme** [comment]
Faster-whisper刚刚发布了新版本，更新了PyAV库，已支持 python 3.12x。
您可以重新运行 `install.bat` 文件，以便在 python 3.12x 环境运行。
