### ISSUE TITLE
【错误】torch+CUDA安装后CUDA加速不可用

### ISSUE THREAD

**Issue by ccchan49** [Chenyme/Chenyme-AAMT#21]
不知为何CUDA+torch正常工作下（）加速的选项不可用
测试Stable-diffusion webui是正常的，

然后人工检查：
import torch
torch.cuda.is_available()
返回True
![image](https://github.com/Chenyme/Chenyme-AAVT/assets/60914289/38dfebec-fb61-4b49-9d8a-aa73308cac3a)

**Comment by ccchan49** [comment]
CUDA版本：12.1， V12.1.66
torch版本：2.2.2+cu121


人工删掉📽️视频(Video).py的`, disabled=not torch.cuda.is_available()`后打开cuda加速测试，出现报错`Could not locate cudnn_ops_infer64_8.dll. Please make sure it is in your library path!`

去nv官网下载cudnn 8.9.7.29后把文件复制进C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1后测试可以正常使用GPU加速识别过程

但是把代码加回去后加速的选项还是不可用

**Comment by chenyme** [comment]
你好！感谢反馈！
请问在测试时环境是否一致？项目的环境基于项目目录下env文件，我看到你的测试是在全局环境下，这可能导致错误的原因。建议在env下启动cmd或powershell测试，如果仍有错误还请继续向我反馈，感谢！

**Comment by ccchan49** [comment]
> 你好！感谢反馈！ 请问在测试时环境是否一致？项目的环境基于项目目录下env文件，我看到你的测试是在全局环境下，这可能导致错误的原因。建议在env下启动cmd或powershell测试，如果仍有错误还请继续向我反馈，感谢！

在env下启动，torch.cuda.is_available()确实返回false

猜测是因为install.bat安装的torch版本有问题，把里面检查/更新的语句换成了torch官网的命令（加上 --force-reinstall）
pip3 install --force-reinstall torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

重新运行install.bat后torch.cuda.is_available()返回true，按钮也正常了

**Comment by chenyme** [comment]
了解了，是我搞忘了这一点，程序默认安装的torch版本是CPU的，后面我会对文档进行补充并做相应调整，感谢！
(｡ì _ í｡)

**Comment by zhao-wuyan** [comment]
> 了解了，是我搞忘了这一点，程序默认安装的torch版本是CPU的，后面我会对文档进行补充并做相应调整，感谢！ (｡ì _ í｡)

我使用anaconda方式安装python依赖。
也遇到`Could not locate cudnn_ops_infer64_8.dll....`这个问题，然后使用`pip3 install --force-reinstall torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121`安装后此问题消失。

还遇到了 https://github.com/Chenyme/Chenyme-AAVT/issues/22#issue-2270809605 中的问题
不过是`libiomp5md.dll`这个文件。我删除了`\Anaconda3\envs\chenyme\Library\bin\libiomp5md.dll` 后正常使用。

但是我选择了gpu加速，使用的还是cpu

![Clip_2024-05-13_11-14-03](https://github.com/Chenyme/Chenyme-AAVT/assets/59789646/1e90c84d-6132-4cd7-9e0b-755e4bb87dc6)
![image](https://github.com/Chenyme/Chenyme-AAVT/assets/59789646/ae2835d9-ab65-42e6-bb07-7346cba5ed36)

**Comment by zhao-wuyan** [comment]
> 但是我选择了gpu加速，使用的还是cpu

这是`ffmpeg`视频转换的过程吗。`ffmpeg`是否也能设置通过gpu进行转换？

**Comment by chenyme** [comment]
> > 但是我选择了gpu加速，使用的还是cpu
> 
> 
> 
> 这是`ffmpeg`视频转换的过程吗。`ffmpeg`是否也能设置通过gpu进行转换？

你好！图片中的过程是ffmpeg的合并过程，ffmpeg支持gpu加速，我会在后续的版本更新这个功能，也欢迎加入我们新建的群聊获得及时回复～
![image](https://github.com/Chenyme/Chenyme-AAVT/assets/118253778/7c28d881-6507-48c4-a4e0-d5d614091c42)
