### ISSUE TITLE
【提问】网页中点击运行程序报错，命令框闪退

### ISSUE THREAD

**Issue by Jieoz** [Chenyme/Chenyme-AAMT#22]
后台命令框内容显示如下
```
oMP: Error #15: Initializing libiomp5nd. d11, but found 1ibiomp5nd. dll already initialized.l oMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpeniP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library, As anunsafe, u nsupported, undocumented workaround you can set the environment variable KMP DUPLICATE LIB OK-TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
```

**Comment by 94ysc** [comment]
开vpn下载模型

**Comment by Jieoz** [comment]
> 开vpn下载模型

下载过了，试了两个模型都是上述错误，下载时正常，下载之后闪退，a卡6800xt

**Comment by chenyme** [comment]
> > 开vpn下载模型
> 
> 下载过了，试了两个模型都是上述错误，下载时正常，下载之后闪退，a卡6800xt

你好！问题可能是由下面的原因导致：PyTorch包中包含了名为`libiomp5nd.dll`的文件，与Anaconda环境中的同名文件出现冲突。

解决方法有如下两种：
1. 在项目文件中添加下面的代码，但注意这不是根本性解决问题的方法。
```
import os
os.environ[“KMP_DUPLICATE_LIB_OK”]=“TRUE”
```

2. 删除其中一个`libiomp5nd.dll`
- 删除项目目录`Chenyme_AAVT_0.6.4\env\Lib\site-packages\torch\lib`下的`libiomp5nd.dll`文件（推荐）
- 或者删除Anaconda下的重复`libiomp5nd.dll`（注意不要删错，否则可能导致其他库不可用或者其他错误）

---

ps：最近比较忙，回的比较晚，抱歉~

**Comment by Jieoz** [comment]
> > > 开vpn下载模型
> > 
> > 下载过了，试了两个模型都是上述错误，下载时正常，下载之后闪退，a卡6800xt
> 
> 你好！问题可能是由下面的原因导致：PyTorch包中包含了名为`libiomp5nd.dll`的文件，与Anaconda环境中的同名文件出现冲突。
> 
> 解决方法有如下两种：
> 1. 在项目文件中添加下面的代码，但注意这不是根本性解决问题的方法。
> ```
> import os
> os.environ[“KMP_DUPLICATE_LIB_OK”]=“TRUE”
> ```
> 
> 2. 删除其中一个`libiomp5nd.dll`
> - 删除项目目录`Chenyme_AAVT_0.6.4\env\Lib\site-packages\torch\lib`下的`libiomp5nd.dll`文件（推荐）
> - 或者删除Anaconda下的重复`libiomp5nd.dll`（注意不要删错，否则可能导致其他库不可用或者其他错误）
> 
> ---
> 
> ps：最近比较忙，回的比较晚，抱歉~

成功了，谢谢大佬。
不过AMD显卡效率有点低，两分半的视频运行了将近十分钟才做出来字幕。
还有请问大佬有没有办法能获取到离线包呢，或者有没有办法导出本机配置完成的安装包，可以直接离线安装使用

**Comment by chenyme** [comment]
不客气😇！
想问下你所说的离线包是指什么？whisper模型么？你也可以加入群聊讨论～
![image](https://github.com/Chenyme/Chenyme-AAVT/assets/118253778/ed134b40-f82f-4c49-85c1-1ddeb76a3a23)

**Comment by Jieoz** [comment]
> 不客气😇！ 想问下你所说的离线包是指什么？whisper模型么？你也可以加入群聊讨论～ ![image](https://private-user-images.githubusercontent.com/118253778/330316860-ed134b40-f82f-4c49-85c1-1ddeb76a3a23.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NTM4MTQsIm5iZiI6MTcxNTc1MzUxNCwicGF0aCI6Ii8xMTgyNTM3NzgvMzMwMzE2ODYwLWVkMTM0YjQwLWY4MmYtNGM0OS04NWMxLTFkZGViNzZhM2EyMy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTVUMDYxMTU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmE5NjJhMzdjOTJmMDJlMzg3MjEyZjQ2MGM1OWQ1NGE1ZGIwZmFmYWE4MWE1NGZhNDhmYThlYjk0OGIyYTg2ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.trHwbbAd-ZBuTC11PFccYLnTmKJ09LNc80UkZiZ2a2Q)

好的大佬
我的想法是把程序所有关联的依赖和模型等数据打包成一个离线安装包，可以在彻底的在网络环境不好或不联网的电脑里使用，不知道有没有办法实现

**Comment by chenyme** [comment]
是可以实现的！我已经在最新版本支持了本地大语言模型接口调用，只不过完全本地化有点复杂，并且需要一定的电脑性能支持。

你需要准备：

1. Faster-whisper相关模型（如Large模型）。
2. 本地大语言模型（如ChatGLM3模型）。
3. 该项目的源码，并提前安装好所有依赖库。

这样就可以实现在网络环境不好或不联网的电脑里使用。但是我觉得如果完全实现必须要依赖GPU，否则这么多项目同时运行，只用CPU电脑完全吃不消的。
