### ISSUE TITLE
【错误】streamlit server can not be connected

### ISSUE THREAD

**Issue by CharlesLieu** [Chenyme/Chenyme-AAMT#23]
开webui后，chrome后台就报错，但是前端能正常交互，但是点击“运行程序”就还是报错

![WeChat Screenshot_20240504165106](https://github.com/Chenyme/Chenyme-AAVT/assets/126322890/81962775-4518-47f9-af27-a4dd1d3c8744)

Failed to load resource: net::ERR_NAME_NOT_RESOLVED
main.eccc579f.js:2 
        
        
       GET http://localhost:8501/%E9%9F%B3%E9%A2%91(Audio)/_stcore/health net::ERR_CONNECTION_REFUSED
(anonymous) @ main.eccc579f.js:2
xhr @ main.eccc579f.js:2
ke @ main.eccc579f.js:2
_request @ main.eccc579f.js:2
request @ main.eccc579f.js:2
P.forEach.Be.<computed> @ main.eccc579f.js:2
(anonymous) @ main.eccc579f.js:2
c @ main.eccc579f.js:2
(anonymous) @ main.eccc579f.js:2
pingServer @ main.eccc579f.js:2
setFsmState @ main.eccc579f.js:2
stepFsm @ main.eccc579f.js:2
websocket.onclose @ main.eccc579f.js:2
main.eccc579f.js:2 
        
        
       GET http://localhost:8501/%E9%9F%B3%E9%A2%91(Audio)/_stcore/host-config net::ERR_CONNECTION_REFUSED

**Comment by chenyme** [comment]
你好！
根据报错显示`Failed to load resource: net::ERR_NAME_NOT_RESOLVED`，这个错误表明尝试连接到localhost的8501端口时被拒绝，或者有防火墙规则阻止了这次连接。请检查chrome的设置，或者能否尝试其他浏览器使用，观察是否有同样错误？
感谢~
