### ISSUE TITLE
【错误】OpenMP

### ISSUE THREAD

**Issue by wuye901126** [Chenyme/Chenyme-AAMT#24]
本地调用模式
加载模型：D:/BigModel/Chenyme-AAVT-main/models/medium
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

**Comment by chenyme** [comment]
你好，该问题您可参考：https://github.com/Chenyme/Chenyme-AAVT/issues/22

问题可能是由下面的原因导致：PyTorch包中包含了名为`libiomp5md.dll`的文件，与Anaconda环境中的同名文件出现冲突。

解决方法有如下两种：
1. 在项目文件中添加下面的代码，但注意这不是根本性解决问题的方法。
```
import os
os.environ[“KMP_DUPLICATE_LIB_OK”]=“TRUE”
```

2. 删除其中一个`libiomp5md.dll`
- 删除项目目录`..\env\Lib\site-packages\torch\lib`下的`libiomp5md.dll`文件（推荐）
- 或者删除Anaconda下的重复`libiomp5md.dll`（注意不要删错，否则可能导致其他库不可用或者其他错误）

如果有更多问题，可以加入群组讨论，或在此继续回复，感谢你的反馈~
