### ISSUE TITLE
【错误】中转站无法正常调用

### ISSUE THREAD

**Issue by FRO4TEN** [Chenyme/Chenyme-AAMT#25]
“视频”模块下开启代理选项仍旧识别为官方API

设置中已正确填写key和api地址

![image](https://github.com/Chenyme/Chenyme-AAVT/assets/108975286/97d6229f-584e-421e-a6e6-0ab7619b0742)

**Comment by chenyme** [comment]
你好！请检查api_key的状态是否可用，或者检查是否有相关模型的使用权限

我刚刚测试了一下，代理模式正常，项目正常运行。
![1715958311584](https://github.com/Chenyme/Chenyme-AAVT/assets/118253778/6b4a7187-cf13-469b-a3da-7686526c791b)

根据你的报错代码401，官方是这样解释的
![1715958457033](https://github.com/Chenyme/Chenyme-AAVT/assets/118253778/4873404d-42b2-437a-b634-bf69c523a5fa)

请仔细检查api_key的状态是否可用，或检查是否有相关模型的使用权限~感谢反馈！

**Comment by FRO4TEN** [comment]
调用的是whisper-1吗？，中转站确认是支持的。
另：没有输出“代理开启“字样
感谢回复😀

**Comment by chenyme** [comment]
不客气～模型是whisper-1，那个提示是我在0.7.1加入的，你可以试试

**Comment by FRO4TEN** [comment]
经检查，是中转站处出现的问题，目前经测试：小海，happy，gptgod等虽表明支持，但实际都无法使用。目前用本地部署whisper+中转站翻译解决

**Comment by chenyme** [comment]
感谢说明！
