### ISSUE TITLE
【提问】点了install.bat完了不会使用，如何卸载？

### ISSUE THREAD

**Issue by fuxin-mail** [Chenyme/Chenyme-AAMT#26]
点了install.bat完了不会使用，我想卸载，如何操作？

**Comment by chenyme** [comment]
你好！

直接删除项目目录下的所有文件即可。

请问项目有什么不明白的地方？以便我后续的改进。

**Comment by fuxin-mail** [comment]
> 你好！
> 
> 直接删除项目目录下的所有文件即可。
> 
> 请问项目有什么不明白的地方？以便我后续的改进。

主要是我小白，基础太差，还得进一步学习哈哈哈

**Comment by fuxin-mail** [comment]
> 你好！
> 
> 直接删除项目目录下的所有文件即可。
> 
> 请问项目有什么不明白的地方？以便我后续的改进。

谢谢回复！

**Comment by chenyme** [comment]
好的没事，后面我会逐步完善一下使用文档，一起加油！
