### ISSUE TITLE
【建议】关于个别bug的探讨

### ISSUE THREAD

**Issue by Ladbaby** [Chenyme/Chenyme-AAMT#28]
首先感谢作者开源了本项目，整体还是非常好用的，个人非常喜欢

下面列出几个我遇到的bug，希望能帮助项目变得更好：
- `project\video.py`: 
    - 64行:  变量 `vad` 的赋值应为boolean而非string，即 `vad = True if VAD_on else False`。在当前实现中，vad无论UI如何选择都会开启
    - 95行：”本地模型“的UI创建中未定义`language2`，将会导致后续调用 `local_translate` 函数出现未定义引用；另外`language = ('中文', 'English', '日本語', '한국인', 'Italiano', 'Deutsch')`也许可以放在更早的位置（如93行）进行赋值，以覆盖不同翻译设置
    
关于翻译使用的prompt，本人测试的时候使用性能较弱的本地部署的ChatGLM3-6B-int4，发现当前prompt的翻译效果并不理想，模型会输出很多废话。个人目前将prompt改成如下，可以实现无废话的翻译：
```
messages=[
    {
        "role": "user",
        "content": f"请将下列括号内的文本翻译为{language2}，只需直接回答翻译后的文本。\n[{text}]"}
])
 ```
 个人意见，仅供参考。

**Comment by chenyme** [comment]
感谢你的建议！
随着项目功能越来越多导致代码很乱，近期我会重构项目，让这个流程更加方便和合理。
我已经注意到这些问题，将会逐步优化。
非常感谢！

**Comment by Ladbaby** [comment]
期待 :）
