### ISSUE TITLE
【建议】希望有docker部署版本

### ISSUE THREAD

**Issue by RedCatJump** [Chenyme/Chenyme-AAMT#29]
rt

**Comment by chenyme** [comment]
你好！
由于目前时间精力有限，但会考虑的~

**Comment by Eisaichen** [comment]
我封了个Windows版的，Win下调用GPU比较方便
https://hub.docker.com/r/eisai/chenyme-aavt

**Comment by RedCatJump** [comment]
> 我封了个Windows版的，Win下调用GPU比较方便
> 
> https://hub.docker.com/r/eisai/chenyme-aavt

感谢大佬！

**Comment by weaming** [comment]
这个 macos 能用吗

**Comment by chenyme** [comment]
> 这个 macos 能用吗

已支持

**Comment by chenyme** [comment]
现已支持 Linux Docker 部署 ~ 还是 [Eisaichen](https://github.com/Eisaichen) 大佬帮忙构建的

**Comment by planet756** [comment]
docker部署点击打开目录按钮提示“未进行识别，目录尚未生成！”，但实际已经生成，建议可以增加直接下载按钮

**Comment by planet756** [comment]
> 现已支持 Linux Docker 部署 ~ 还是 [Eisaichen](https://github.com/Eisaichen) 大佬帮忙构建的

docker部署点击打开目录按钮提示“未进行识别，目录尚未生成！”，但实际已经生成，建议可以增加直接下载按钮
