### ISSUE TITLE
【错误】关于文字的上限

### ISSUE THREAD

**Issue by zhang19910715** [Chenyme/Chenyme-AAMT#3]
若使用kimi进行翻译，如果字幕超过一定数量之后，就无法进行翻译了，例如，一个视频超过10分钟，之后，就没办法进行翻译了，所提供的字幕就是还是英文的

**Comment by chenyme** [comment]
您好！我在V0.5.1版本中优化了kimi的调用逻辑，已测试可实现30min的正确的中英文翻译，现在上限保守来说在4w-5w字左右。后续版本我会开放调节最大字数。^^~
