### ISSUE TITLE
【建议】希望能支持音频直接提取字幕的功能

### ISSUE THREAD

**Issue by midpoint** [Chenyme/Chenyme-AAMT#33]
现在只支持视频文件上传转换，希望能支持音频直接提取字幕的功能

**Comment by chenyme** [comment]
你好！感谢反馈！
下个版本我会将**音频识别**模块重新制作上架，预计明天或者后天发布🥰

**Comment by chenyme** [comment]
新版本[V0.8.4](https://github.com/Chenyme/Chenyme-AAVT/releases/tag/V0.8.4)已发布！已支持音频直接提取字幕！

**Comment by midpoint** [comment]
太给力了，感谢！
