### ISSUE TITLE
【建议】希望在翻译时允许使用自定义的提示词

### ISSUE THREAD

**Issue by MaleicAcid** [Chenyme/Chenyme-AAMT#34]
在翻译时，希望能够使用自定义的提示词, 以便向AI指明待翻译文字的专业领域，特定的术语词汇，目标文字的语言风格等翻译需求，优化翻译效果。

**Comment by chenyme** [comment]
你好！感谢反馈！
下个版本中会增加**预置提示词**的功能，支持分享和导入提示词，敬请期待哟～

**Comment by chenyme** [comment]
新版本[V0.8.4](https://github.com/Chenyme/Chenyme-AAVT/releases/tag/V0.8.4)已发布！支持使用自定义的提示词
