### ISSUE TITLE
【建议】希望支持使用Google Gemini /Gemini pro进行翻译

### ISSUE THREAD

**Issue by MaleicAcid** [Chenyme/Chenyme-AAMT#35]
Gemini pro 目前有一定的免费额度，功能与 GPT4 类似。
希望增加对 [Gemini Pro API](https://ai.google.dev/) 的支持，可参考[文档](https://ai.google.dev/tutorials/node_quickstart?hl=zh-cn)。

**Comment by chenyme** [comment]
你好！感谢反馈！
项目这两天会更新，但由于没有gemini账号，无法测试稳定性。目前借助中转站测试能成功运行。

**Comment by chenyme** [comment]
新版本[V0.8.4](https://github.com/Chenyme/Chenyme-AAVT/releases/tag/V0.8.4)已发布！支持使用Google Gemini /Gemini pro进行翻译。
