### ISSUE TITLE
【提问】aavt出现这种情况该怎么办

### ISSUE THREAD

**Issue by 6sjsj** [Chenyme/Chenyme-AAMT#41]
<img width="976" alt="屏幕截图 2024-07-09 212423" src="https://github.com/Chenyme/Chenyme-AAVT/assets/110598050/91b1d9a9-14b2-40f9-817e-a815ff3a5388">

**Comment by chenyme** [comment]
您好！请查看 [此文档](https://zwho5v3j233.feishu.cn/wiki/C7akw4w44iFEEPky8fScjqFWnbf?from=from_copylink) 的 `Part 3 运行识别` 中的 `第一条`
