### ISSUE TITLE
【建议】希望可以增加docker

### ISSUE THREAD

**Issue by dhlsam** [Chenyme/Chenyme-AAMT#5]
非常好的自动化项目，希望可以增加docker的安装方式，这样可以在服务器运行

**Comment by chenyme** [comment]
你好！感谢你的支持和建议，我会考虑在后续版本中增加Docker的安装方式。
但是由于本项目需要使用Whisper和FFmpeg，考虑到服务器性能状态，在服务器上运行本项目可能会导致CPU负载过高、内存占用较大，且难以调用GPU，导致生成失败或者速度过慢。
因此建议在使用时尽量避免在服务器上直接运行。后续我会继续优化压缩。

**Comment by dhlsam** [comment]
> 你好！感谢你的支持和建议，我会考虑在后续版本中增加Docker的安装方式。 但是由于本项目需要使用Whisper和FFmpeg，考虑到服务器性能状态，在服务器上运行本项目可能会导致CPU负载过高、内存占用较大，且难以调用GPU，导致生成失败或者速度过慢。 因此建议在使用时尽量避免在服务器上直接运行。后续我会继续优化压缩。

感谢，这样也方便在linux系统里直接运行
