### ISSUE TITLE
【错误】本地模型调用视频翻译时候提示错误

### ISSUE THREAD

**Issue by JiangTaoShi** [Chenyme/Chenyme-AAMT#50]
![image](https://github.com/user-attachments/assets/1215a244-8842-4188-97f0-7b603f895624)
![image](https://github.com/user-attachments/assets/92192dfa-1c99-4a24-802d-4f10e64300bb)
![image](https://github.com/user-attachments/assets/4661a802-067a-4edf-9d96-73502e201e2c)
![image](https://github.com/user-attachments/assets/1a039fdb-3261-4d1e-910f-7ed1a4ebea83)
![image](https://github.com/user-attachments/assets/59126cff-83b7-4596-97ae-a4a7271ef3d7)

**Comment by chenyme** [comment]
你好！你好像误解了项目的调用方式~
主页-设置里的参数主要为翻译模型的参数，而非识别。翻译模型参数请自行前往各大服务商官网申请key并填入，如果您想使用本地模型翻译，请自行部署相关开源模型再配置此参数。

若仍有疑问欢迎继续提问，也建议您阅读此[全流程使用教程](https://blog.chenyme.top/blog/aavt-install#da4eb60ae85d)

**Comment by dhlsam** [comment]
本地模型调用ollama 测试显示正常，但是翻译的时候没有调用

**Comment by chenyme** [comment]
> 本地模型调用ollama 测试显示正常，但是翻译的时候没有调用

你好👋能否提供相关细节，如cmd日志？

**Comment by chenyme** [comment]
> 本地模型调用ollama 测试显示正常，但是翻译的时候没有调用

已定位并修复，刚刚已发布新的软件包，请重新下载安装，感谢你的反馈~
