### ISSUE TITLE
【提问】kimi 是哪个平台?

### ISSUE THREAD

**Issue by jinwyp** [Chenyme/Chenyme-AAMT#6]
建议写到readme 里面 
kimi 是哪个平台 链接是什么?

**Comment by chenyme** [comment]
你好！感谢你的建议。
Kimi 是由月之暗面（Moonshot AI）提供的超长记忆 AI 助手，支持约 20 万汉字的上下文输入，具备显著的中文优势，随时为你回答问题、速读文件、整理资料、激发灵感、辅助创作。 你可以与 Kimi 聊天，发送网址链接，上传文件。
moonshot官网：https://www.moonshot.cn/
kimi官网：https://kimi.moonshot.cn/
