### ISSUE TITLE
【提问】有命令行直接能运行的模式吗

### ISSUE THREAD

**Issue by NeetMochi** [Chenyme/Chenyme-AAMT#7]
挂着程序在后台跑了两个多小时顺便看了部电影, 然后edge直接把挂在后台的标签页杀了, 命令行窗口还能看到网页上显示的东西全都跟被重置了一样. 程序跑完的结果根本看不到.

**Comment by chenyme** [comment]
你好！感谢反馈。后续会增加命令行运行模式。
方便问一下edge杀后台是什么原因导致的么？这种情况我还没遇到过。

**Comment by NeetMochi** [comment]
可能是休眠不活动标签页功能, 我之前忘了有这回事没加白名单.
![QQ截图20240225210651](https://github.com/Chenyme/Chenyme-AAVT/assets/96508493/53fc9e2d-7b10-413e-9fce-eb9fa43527a1)

**Comment by chenyme** [comment]
已发布了python包~
